version: "3.9"
services:
  api:
    build: ../apps/api
    env_file: ../.env
    ports: ["8000:8000"]
    depends_on: [mongo, redis, qdrant]
  worker:
    build: ../apps/worker
    env_file: ../.env
    depends_on: [api, mongo, redis, qdrant]
  scheduler:
    build: ../apps/scheduler
    env_file: ../.env
    depends_on: [api, redis]
  mongo:
    image: mongo:7
    volumes: ["mongo_data:/data/db"]
  redis:
    image: redis:7
  qdrant:
    image: qdrant/qdrant:latest
    volumes: ["qdrant_data:/qdrant/storage"]
  # nginx:
  #   image: nginx:stable
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports: ["8080:80","8443:443"]
  #   depends_on: [api]
  prometheus:
    image: prom/prometheus
    volumes: ["./prometheus.yml:/etc/prometheus/prometheus.yml:ro"]
    ports: ["9090:9090"]
  grafana:
    image: grafana/grafana
    ports: ["3000:3000"]
volumes:
  mongo_data:
  qdrant_data:
